import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { Archive, Copy, Pause, Play } from "lucide-react";
import AppShell from "@/components/app/AppShell";
import DeleteFlowModal from "@/components/dashboard/DeleteFlowModal";
import SetBudgetModal from "@/components/dashboard/SetBudgetModal";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";

type Flow={id:string;name:string;platform:string;model:string;flow_enabled:boolean;control_state:string;environment:string;approval_status:string;protection_mode:string;archived_at:string|null;description:string|null;business_purpose:string|null;team_label:string|null;budget_limit:number|null;daily_budget_limit:number|null};
type Run={id:string;status:string;duration_ms:number;token_count:number;cost_usd:number;created_at:string;source:string};
type Summary={total_cost_usd:number;today_runs:number;today_cost_usd:number;week_runs:number;week_cost_usd:number;month_runs:number;month_cost_usd:number};
const box="rounded-lg border border-slate-200 bg-white p-5";

export default function FlowDetail(){
 const{id}=useParams<{id:string}>();const[searchParams]=useSearchParams();const{user,loading:authLoading,signOut}=useAuth();const navigate=useNavigate();
 const[flow,setFlow]=useState<Flow|null>(null),[runs,setRuns]=useState<Run[]>([]),[summary,setSummary]=useState<Summary|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[tab,setTab]=useState(()=>searchParams.get("tab")==="settings"?"settings":"overview");
 const[copied,setCopied]=useState(false),[budgetOpen,setBudgetOpen]=useState(false),[archiveOpen,setArchiveOpen]=useState(false),[saved,setSaved]=useState(false);
 const[name,setName]=useState(""),[platform,setPlatform]=useState(""),[model,setModel]=useState(""),[team,setTeam]=useState(""),[purpose,setPurpose]=useState(""),[description,setDescription]=useState("");
 const endpoint=`${import.meta.env.VITE_SUPABASE_URL||"https://your-project.supabase.co"}/functions/v1/ingest/${id}`;
 const load=useCallback(async()=>{if(!id||!user)return;setError(null);const[f,r,s]=await Promise.all([supabase.from("flows").select("*").eq("id",id).single(),supabase.from("runs").select("id,status,duration_ms,token_count,cost_usd,created_at,source").eq("flow_id",id).neq("source","synthetic_demo").order("created_at",{ascending:false}).limit(50),supabase.rpc("get_flow_detail_summary",{p_flow_id:id})]);if(f.error||!f.data){setError(f.error?.message??"Workflow not found");setLoading(false);return;}const x=f.data as Flow;setFlow(x);setRuns((r.data??[])as Run[]);setSummary(s.data as Summary|null);setName(x.name);setPlatform(x.platform);setModel(x.model);setTeam(x.team_label??"");setPurpose(x.business_purpose??"");setDescription(x.description??"");setLoading(false);},[id,user]);
 useEffect(()=>{void load()},[load]);
 const toggle=async()=>{if(!flow)return;setSaving(true);const action=flow.flow_enabled?"pause":"resume",r=await supabase.rpc("set_flow_control",{p_flow_id:flow.id,p_action:action,p_reason:`${action} from workflow detail`});if(r.error)setError(r.error.message);else await load();setSaving(false)};
 const save=async()=>{if(!flow||!name.trim())return;setSaving(true);setSaved(false);const r=await supabase.from("flows").update({name:name.trim(),platform:platform.trim(),model:model.trim(),team_label:team.trim()||null,business_purpose:purpose.trim()||null,description:description.trim()||null}).eq("id",flow.id);if(r.error)setError(r.error.message);else{setSaved(true);await load()}setSaving(false)};
 if(authLoading||loading)return <div className="min-h-screen bg-[#f7f8fa] p-8"><div className="mx-auto h-96 max-w-6xl animate-pulse rounded-lg bg-white"/></div>;
 if(!flow)return <AppShell userLabel={user?.email} onSignOut={signOut}><div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error??"Workflow not found."}</div></AppShell>;
 const status=flow.archived_at?"Archived":flow.control_state==="emergency_stopped"?"Emergency stopped":flow.flow_enabled?"Running":"Paused",field="mt-1 h-9 w-full rounded-md border border-slate-300 px-3 text-sm";
 return <AppShell userLabel={user?.email} onSignOut={signOut}><div className="space-y-5">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-xl font-semibold">{flow.name}</h1><span className="rounded-full border px-2 py-0.5 text-[10px] font-semibold">{status}</span></div><p className="mt-1 text-xs text-slate-500">{flow.platform} · {flow.model||"Unknown model"} · {flow.environment} · {flow.approval_status}</p></div><div className="flex gap-2"><button onClick={toggle} disabled={saving||!!flow.archived_at} className="inline-flex h-9 items-center gap-1 rounded-md border px-3 text-xs font-semibold disabled:opacity-50">{flow.flow_enabled?<Pause className="h-3.5 w-3.5"/>:<Play className="h-3.5 w-3.5"/>}{flow.flow_enabled?"Pause":"Resume"}</button><button onClick={()=>setTab("settings")} className="h-9 rounded-md bg-blue-600 px-3 text-xs font-semibold text-white">Edit workflow</button></div></header>
  {error?<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-800">{error}</div>:null}
  <Tabs value={tab} onValueChange={setTab}><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-none border-b bg-transparent p-0">{["overview","activity","spending","controls","settings"].map(v=><TabsTrigger key={v} value={v} className="capitalize">{v}</TabsTrigger>)}</TabsList>
   <TabsContent value="overview" className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><section className={box}><h2 className="text-sm font-semibold">Workflow overview</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[["Description",flow.description||"Not provided"],["Responsibility",flow.business_purpose||"Not provided"],["Owner / team",flow.team_label||"Unassigned"],["Protection",flow.protection_mode]].map(([a,b])=><div key={a}><dt className="text-[10px] font-semibold uppercase text-slate-400">{a}</dt><dd className="mt-1 text-sm">{b}</dd></div>)}</dl></section><section className={box}><h2 className="text-sm font-semibold">Current period</h2><div className="mt-4 space-y-3">{[["Today",summary?.today_runs,summary?.today_cost_usd],["This week",summary?.week_runs,summary?.week_cost_usd],["This month",summary?.month_runs,summary?.month_cost_usd]].map(([a,b,c])=><div key={String(a)} className="flex justify-between border-b pb-2 text-sm"><span>{a}: {b??"—"} runs</span><strong>{c==null?"—":`$${Number(c).toFixed(2)}`}</strong></div>)}</div></section></TabsContent>
   <TabsContent value="activity" className="mt-5"><section className="overflow-hidden rounded-lg border bg-white"><h2 className="border-b p-4 text-sm font-semibold">Recent reported activity</h2><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-xs"><thead><tr>{["Time","Status","Duration","Tokens","Cost","Source"].map(x=><th key={x} className="px-4 py-3 text-left">{x}</th>)}</tr></thead><tbody>{runs.map(r=><tr key={r.id} className="border-t"><td className="px-4 py-3">{new Date(r.created_at).toLocaleString()}</td><td>{r.status}</td><td>{r.duration_ms}ms</td><td>{r.token_count}</td><td>${Number(r.cost_usd).toFixed(4)}</td><td>{r.source}</td></tr>)}{!runs.length?<tr><td colSpan={6} className="p-8 text-center text-slate-400">No reported activity yet.</td></tr>:null}</tbody></table></div></section></TabsContent>
   <TabsContent value="spending" className="mt-5 grid gap-4 sm:grid-cols-3">{[["Observed total",summary?.total_cost_usd],["Daily budget",flow.daily_budget_limit],["Monthly budget",flow.budget_limit]].map(([a,b])=><div key={String(a)} className={box}><div className="text-xs text-slate-500">{a}</div><div className="mt-2 text-2xl font-semibold">{b==null?"Not set":`$${Number(b).toFixed(2)}`}</div></div>)}</TabsContent>
   <TabsContent value="controls" className="mt-5"><section className={box}><h2 className="text-sm font-semibold">Execution controls</h2><p className="mt-2 text-xs text-slate-500">Pause blocks new admissions only when the runner uses FlowLedger guard protection.</p><button onClick={toggle} className="mt-4 h-9 rounded-md border px-3 text-xs font-semibold">{flow.flow_enabled?"Pause new admissions":"Resume workflow"}</button></section></TabsContent>
   <TabsContent value="settings" className="mt-5 space-y-4"><section className={box}><h2 className="text-sm font-semibold">Identity and responsibility</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs">Name<input className={field} value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-xs">Owner / team<input className={field} value={team} onChange={e=>setTeam(e.target.value)} placeholder="Maya · Operations"/></label><label className="text-xs">Platform<input className={field} value={platform} onChange={e=>setPlatform(e.target.value)}/></label><label className="text-xs">Model<input className={field} value={model} onChange={e=>setModel(e.target.value)}/></label><label className="text-xs sm:col-span-2">Responsibility<textarea className="mt-1 w-full rounded-md border px-3 py-2" rows={2} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label className="text-xs sm:col-span-2">Description<textarea className="mt-1 w-full rounded-md border px-3 py-2" rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></label></div><div className="mt-4 flex items-center gap-3"><button onClick={save} disabled={saving||!name.trim()} className="h-9 rounded-md bg-blue-600 px-4 text-xs font-semibold text-white">Save details</button>{saved?<span className="text-xs text-emerald-700">Saved.</span>:null}</div></section>
    <section className={box}><div className="flex items-center justify-between gap-4"><div><h2 className="text-sm font-semibold">Budgets and protection</h2><p className="mt-1 text-xs text-slate-500">Daily {flow.daily_budget_limit==null?"not set":`$${flow.daily_budget_limit}`} · Monthly {flow.budget_limit==null?"not set":`$${flow.budget_limit}`} · {flow.protection_mode}</p></div><button onClick={()=>setBudgetOpen(true)} className="h-9 rounded-md border px-3 text-xs font-semibold">Edit budgets</button></div></section>
    <section className={box}><h2 className="text-sm font-semibold">Reporting connection</h2><p className="mt-1 text-xs text-slate-500">Changing a platform label does not connect a provider. Use a scoped credential and stable event IDs.</p><div className="mt-4 flex gap-2 rounded-md border bg-slate-50 p-3"><code className="min-w-0 flex-1 break-all text-[11px]">POST {endpoint}</code><button aria-label="Copy reporting endpoint" onClick={async()=>{await navigator.clipboard.writeText(endpoint);setCopied(true);setTimeout(()=>setCopied(false),1200)}}><Copy className="h-4 w-4"/></button></div><div className="mt-3 flex gap-3"><Link to={`/setup?flow=${flow.id}`} className="text-xs font-semibold text-blue-600">Open connection setup →</Link>{copied?<span className="text-xs text-emerald-700">Copied.</span>:null}</div></section>
    <section className="rounded-lg border border-red-200 bg-white p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="text-sm font-semibold">Archive workflow</h2><p className="mt-1 text-xs text-slate-500">Removes it from active work while preserving activity, costs, and incidents.</p></div><button onClick={()=>setArchiveOpen(true)} className="inline-flex h-9 items-center gap-1 rounded-md border border-red-300 px-3 text-xs font-semibold text-red-700"><Archive className="h-3.5 w-3.5"/>Archive</button></div></section>
   </TabsContent>
  </Tabs>
 </div>{budgetOpen?<SetBudgetModal flowId={flow.id} flowName={flow.name} currentBudget={flow.budget_limit} currentDailyBudget={flow.daily_budget_limit} currentProtectionMode={flow.protection_mode} onClose={()=>setBudgetOpen(false)} onSaved={()=>{setBudgetOpen(false);void load()}}/>:null}{archiveOpen?<DeleteFlowModal flowId={flow.id} flowName={flow.name} onClose={()=>setArchiveOpen(false)} onDeleted={()=>navigate("/dashboard")}/>:null}</AppShell>
}
