import { Link } from "react-router-dom";
import AppShell from "@/components/app/AppShell";
import { useAuth } from "@/hooks/useAuth";

type Mode = "demo" | "preview" | "account";

export default function ProductHelp({ mode }: { mode: Mode }) {
  const { user, signOut } = useAuth(false); const demo = mode === "demo"; const preview = mode === "preview"; const overview = demo ? "/demo" : "/dashboard";
  return <AppShell workspaceLabel={demo ? "Demo workspace" : preview ? "Preview account" : "My workspace"} userLabel={preview || mode === "account" ? user?.email : undefined} preview={preview} demo={demo} onSignOut={preview || mode === "account" ? signOut : undefined}><div className="mx-auto max-w-3xl space-y-6"><div><Link to={overview} className="text-xs font-semibold text-blue-600">← Back to overview</Link><h1 className="mt-3 text-2xl font-semibold tracking-[-.02em]">Help</h1><p className="mt-2 text-sm leading-6 text-slate-600">Use FlowLedger to see what your AI workflows cost, who owns them, and where a decision is needed.</p></div>
    <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-slate-200 bg-white p-4"><div className="text-sm font-semibold">1. Start in Overview</div><p className="mt-2 text-xs leading-5 text-slate-500">See spending, active workflows, and anything that needs attention.</p></div><div className="rounded-lg border border-slate-200 bg-white p-4"><div className="text-sm font-semibold">2. Open a workflow</div><p className="mt-2 text-xs leading-5 text-slate-500">Use its detail page to understand activity, spend, protection, and setup.</p></div><div className="rounded-lg border border-slate-200 bg-white p-4"><div className="text-sm font-semibold">3. Complete reviews</div><p className="mt-2 text-xs leading-5 text-slate-500">Assign an owner and set the next review date for a trial workflow.</p></div></section>
    <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">What budget protection means</h2><p className="mt-2 text-sm leading-6 text-slate-600">For a connected workflow, FlowLedger can stop a new AI call before it begins when its policy denies it. Calls already running may finish. It does not cancel an unconnected external workflow.</p>{demo || preview ? <Link to={demo ? "/demo/replay?mode=demo" : "/demo/replay?mode=preview"} className="mt-4 inline-flex h-9 items-center rounded-md bg-blue-600 px-3 text-xs font-semibold text-white">View the synthetic example</Link> : null}</section>
    <details className="rounded-lg border border-slate-200 bg-white p-5"><summary className="cursor-pointer text-sm font-semibold text-slate-800">Technical connection reference</summary><div className="mt-4 space-y-3 text-sm leading-6 text-slate-600"><p>Ask the technical owner of a workflow to create a scoped credential, then send authenticated activity records after each execution. A stable event ID prevents duplicate records.</p><p>Connection details belong in the workflow’s Settings tab. This guide deliberately keeps credentials and endpoints out of the manager-facing overview.</p></div></details>
  </div></AppShell>;
}
