import { useMemo } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useNavigate } from "react-router-dom";
import AppShell from "@/components/app/AppShell";
import { useAuth } from "@/hooks/useAuth";
import { sampleScenarioLabel, sampleWorkspaceMetrics, useSampleWorkspace, type SampleMode } from "@/lib/demo/workspace";

const baseChartData = [{ label: "Mon", cost: .52 }, { label: "Tue", cost: .74 }, { label: "Wed", cost: .66 }, { label: "Thu", cost: 1.08 }, { label: "Fri", cost: 1.21 }, { label: "Sat", cost: .59 }, { label: "Sun", cost: .72 }];
const money = (value: number) => `$${value.toFixed(2)}`;

export default function SampleSpending({ mode }: { mode: SampleMode }) {
  const demo = mode === "demo"; const navigate = useNavigate(); const { workspace, reset } = useSampleWorkspace(mode); const { signOut } = useAuth(false); const metrics = sampleWorkspaceMetrics(workspace); const multiplier = workspace.scenario === "week" ? 3 : workspace.scenario === "month" ? 12 : 1; const chartData = baseChartData.map((point) => ({ ...point, cost: point.cost * multiplier }));
  const rows = useMemo(() => [...workspace.flows].sort((a, b) => (b.spend ?? 0) - (a.spend ?? 0)), [workspace.flows]);
  const detailPath = (id: string) => demo ? `/demo/flows/${id}` : `/flows/${id}`;
  return <AppShell workspaceLabel={demo ? "Demo workspace" : "Preview account"} userLabel={demo ? undefined : "test@gmail.com"} preview demo={demo} onSignOut={demo ? undefined : signOut} onReset={reset}><div className="space-y-5"><div><h1 className="text-xl font-semibold tracking-[-.02em]">Spending</h1><p className="mt-1 text-xs text-slate-500">{sampleScenarioLabel(workspace.scenario)} · reported spending by workflow · illustrative sample data.</p></div>
    <section className="grid overflow-hidden rounded-lg border border-slate-200 bg-white sm:grid-cols-3 sm:divide-x sm:divide-slate-200"><div className="border-b border-slate-200 p-4 sm:border-b-0"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Reported spend</div><div className="mt-2 text-2xl font-semibold tabular-nums">{money(metrics.spend)}</div></div><div className="border-b border-slate-200 p-4 sm:border-b-0"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Workflows with activity</div><div className="mt-2 text-2xl font-semibold tabular-nums">{workspace.flows.filter((flow) => flow.executions > 0).length}</div></div><div className="p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Executions in sample</div><div className="mt-2 text-2xl font-semibold tabular-nums">{metrics.executions}</div></div></section>
    <section className="rounded-lg border border-slate-200 bg-white p-4"><div><h2 className="text-sm font-semibold">Spend over time</h2><p className="mt-0.5 text-[11px] text-slate-400">This chart uses the same loaded sample scenario as Overview and workflow details.</p></div><div className="mt-4 h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ left: -15, right: 4 }}><CartesianGrid vertical={false} stroke="#e8edf3"/><XAxis dataKey="label" tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false}/><YAxis tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false} tickFormatter={(value) => `$${value}`}/><Tooltip formatter={(value: number) => [money(value), "Reported spend"]} contentStyle={{ border: "1px solid #e2e8f0", borderRadius: 6, fontSize: 11 }}/><Bar dataKey="cost" fill="#2563eb" radius={[3, 3, 0, 0]}/></BarChart></ResponsiveContainer></div></section>
    <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-semibold">Where the money went</h2><p className="mt-0.5 text-[11px] text-slate-400">Select a workflow for its activity and controls.</p></div><div className="divide-y divide-slate-100">{rows.map((flow) => <button type="button" key={flow.id} onClick={() => navigate(detailPath(flow.id))} className="grid w-full grid-cols-[minmax(0,1fr)_auto] gap-4 px-4 py-3 text-left transition-colors hover:bg-blue-50/40"><div className="min-w-0"><div className="truncate text-sm font-medium">{flow.name}</div><div className="mt-0.5 text-xs text-slate-400">{flow.owner} · {flow.executions} executions</div></div><div className="text-right"><div className="text-sm font-semibold tabular-nums">{money(flow.spend ?? 0)}</div><div className="mt-0.5 text-[10px] text-slate-400">{flow.budget === null ? "No budget set" : `${money(flow.budget)} budget`}</div></div></button>)}</div></section>
  </div></AppShell>;
}
