import { useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ChevronDown, Pause, Play, ShieldCheck } from "lucide-react";
import AppShell from "@/components/app/AppShell";
import { useAuth } from "@/hooks/useAuth";
import { useSampleWorkspace, type SampleMode } from "@/lib/demo/workspace";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const money = (value: number | null) => value === null ? "Not set" : `$${value.toFixed(2)}`;

export default function SampleFlowDetail({ mode }: { mode: SampleMode }) {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const [searchParams] = useSearchParams(); const { workspace, update, reset } = useSampleWorkspace(mode); const { signOut } = useAuth(false); const [showGuide, setShowGuide] = useState(false);
  const flow = workspace.flows.find((item) => item.id === id);
  const demo = mode === "demo"; const root = demo ? "/demo" : "/dashboard"; const reviewPath = demo ? "/demo/management" : "/command-center";
  if (!flow) return <AppShell workspaceLabel={demo ? "Demo workspace" : "Preview account"} preview demo={demo} onSignOut={demo ? undefined : signOut} onReset={reset}><div className="rounded-lg border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><h1 className="font-semibold">Workflow not found</h1><p className="mt-1">It may have been removed when the sample was reset.</p><Link to={root} className="mt-4 inline-block text-xs font-semibold text-blue-700">Return to overview</Link></div></AppShell>;
  const paused = flow.status === "Paused";
  const updateFlow = (changes: Partial<typeof flow>) => update((current) => ({ flows: current.flows.map((item) => item.id === flow.id ? { ...item, ...changes } : item) }));
  const toggle = () => updateFlow(paused ? { status: flow.issue ? "Needs attention" : "Live", activityNote: "New calls may run again when the connected workflow checks in." } : { status: "Paused", activityNote: "New calls are paused in this sample workspace." });
  const resumeAfterReview = () => updateFlow({ status: "Live", issue: undefined, activityNote: "The issue was reviewed. New calls may resume in this sample workspace." });
  return <AppShell workspaceLabel={demo ? "Demo workspace" : "Preview account"} userLabel={demo ? undefined : "test@gmail.com"} preview demo={demo} onSignOut={demo ? undefined : signOut} onReset={reset}><div className="space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><Link to={root} className="text-xs font-semibold text-blue-600">← Back to overview</Link><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-xl font-semibold tracking-[-.02em]">{flow.name}</h1><span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold ${flow.issue ? "border-amber-200 bg-amber-50 text-amber-700" : paused ? "border-slate-200 bg-slate-100 text-slate-600" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{flow.issue ? "Needs attention" : paused ? "Paused" : "In good standing"}</span></div><p className="mt-1 text-xs text-slate-500">{flow.owner} · {flow.team || "No team"} · {flow.environment}</p></div><button type="button" onClick={toggle} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-md border border-slate-300 bg-white px-3 text-xs font-semibold text-slate-700"><>{paused ? <Play className="h-3.5 w-3.5" /> : <Pause className="h-3.5 w-3.5" />}</>{paused ? "Allow new calls" : "Pause new calls"}</button></div>
    {flow.issue ? <section className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-amber-700" /><div><h2 className="text-sm font-semibold text-amber-950">Review needed</h2><p className="mt-1 text-xs leading-5 text-amber-900">{flow.issue}</p><p className="mt-2 text-xs text-amber-800">In this sample, protection stopped the next connected call before it started. Calls already running may finish.</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={resumeAfterReview} className="h-8 rounded-md bg-amber-800 px-3 text-xs font-semibold text-white">Review and resume new calls</button><Link to="/demo/replay" className="inline-flex h-8 items-center rounded-md border border-amber-300 px-3 text-xs font-semibold text-amber-900">View example replay</Link></div></div></div></section> : null}
    <Tabs defaultValue={searchParams.get("tab") === "settings" ? "settings" : "summary"}><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-none border-b border-slate-200 bg-transparent p-0"><TabsTrigger value="summary" className="rounded-none border-b-2 border-transparent px-4 py-2.5 text-xs data-[state=active]:border-blue-600 data-[state=active]:bg-transparent data-[state=active]:text-blue-700 data-[state=active]:shadow-none">Summary</TabsTrigger><TabsTrigger value="activity" className="rounded-none border-b-2 border-transparent px-4 py-2.5 text-xs data-[state=active]:border-blue-600 data-[state=active]:bg-transparent data-[state=active]:text-blue-700 data-[state=active]:shadow-none">Activity</TabsTrigger><TabsTrigger value="controls" className="rounded-none border-b-2 border-transparent px-4 py-2.5 text-xs data-[state=active]:border-blue-600 data-[state=active]:bg-transparent data-[state=active]:text-blue-700 data-[state=active]:shadow-none">Controls</TabsTrigger><TabsTrigger value="settings" className="rounded-none border-b-2 border-transparent px-4 py-2.5 text-xs data-[state=active]:border-blue-600 data-[state=active]:bg-transparent data-[state=active]:text-blue-700 data-[state=active]:shadow-none">Settings</TabsTrigger></TabsList>
      <TabsContent value="summary" className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">What this workflow does</h2><p className="mt-2 text-sm leading-6 text-slate-600">{flow.description}</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Where it runs</dt><dd className="mt-1 text-sm text-slate-700">{flow.platform} · {flow.model}</dd></div><div><dt className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Protection</dt><dd className="mt-1 text-sm text-slate-700">{flow.protection}</dd></div><div><dt className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Owner</dt><dd className="mt-1 text-sm text-slate-700">{flow.owner}</dd></div><div><dt className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Review status</dt><dd className="mt-1 text-sm text-slate-700">{flow.reviewStatus}</dd></div></dl></section><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">Selected period</h2><div className="mt-4 space-y-3"><div className="flex justify-between border-b border-slate-100 pb-2 text-sm"><span className="text-slate-500">Reported spend</span><strong>{money(flow.spend)}</strong></div><div className="flex justify-between border-b border-slate-100 pb-2 text-sm"><span className="text-slate-500">Executions</span><strong>{flow.executions}</strong></div><div className="flex justify-between border-b border-slate-100 pb-2 text-sm"><span className="text-slate-500">Budget</span><strong>{money(flow.budget)}</strong></div></div></section></TabsContent>
      <TabsContent value="activity" className="mt-5"><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">Recent activity</h2><p className="mt-1 text-xs text-slate-500">{flow.activityNote}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-md bg-slate-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Executions</div><div className="mt-1 text-lg font-semibold">{flow.executions}</div></div><div className="rounded-md bg-slate-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Reported spend</div><div className="mt-1 text-lg font-semibold">{money(flow.spend)}</div></div><div className="rounded-md bg-slate-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Last update</div><div className="mt-1 text-lg font-semibold">Today</div></div></div></section></TabsContent>
      <TabsContent value="controls" className="mt-5"><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">Budget protection</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{flow.protection === "Budget protection connected" ? "Stops new calls from this connected workflow when the policy denies them. Calls already running may finish." : "This workflow is being tracked, but budget protection is not connected yet."}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={toggle} className="h-9 rounded-md border border-slate-300 px-3 text-xs font-semibold">{paused ? "Allow new calls" : "Pause new calls"}</button>{flow.reviewStatus === "Needs review" ? <Link to={reviewPath} className="inline-flex h-9 items-center rounded-md bg-blue-600 px-3 text-xs font-semibold text-white">Open review</Link> : null}</div></section></TabsContent>
      <TabsContent value="settings" className="mt-5"><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">{demo ? "Demo connection note" : "Connect a provider"}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{demo ? "This workflow uses generated sample values. It is not connected to a provider and no data is sent anywhere." : `Connect the ${flow.platform} workflow before FlowLedger can receive activity. Until then, reported spend and budgets remain empty.`}</p><button type="button" onClick={() => setShowGuide((value) => !value)} className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-blue-600">{demo ? "About this demo" : "Connector instructions"} <ChevronDown className={`h-3.5 w-3.5 transition-transform ${showGuide ? "rotate-180" : ""}`} /></button>{showGuide ? <div className="mt-3 rounded-md bg-slate-50 p-3 text-xs leading-5 text-slate-600">{demo ? "Demo values are local to this browser and can be removed with Reset sample." : "Choose the provider connection for this workflow, create a scoped credential, then configure the workflow to send authenticated activity. The endpoint and event format are available in Help for the technical implementer."}</div> : null}</section></TabsContent>
    </Tabs>
  </div></AppShell>;
}
