import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { CheckCircle2, X } from "lucide-react";
import AppShell from "@/components/app/AppShell";
import { useAuth } from "@/hooks/useAuth";
import { sampleWorkspaceMetrics, useSampleWorkspace, type SampleFlow, type SampleMode, type SampleReviewStatus } from "@/lib/demo/workspace";

type ReviewDraft = { flow: SampleFlow; decision: SampleReviewStatus; owner: string; date: string; note: string };

export default function SampleReviews({ mode }: { mode: SampleMode }) {
  const demo = mode === "demo"; const navigate = useNavigate(); const { workspace, update, reset } = useSampleWorkspace(mode); const { signOut } = useAuth(false); const [draft, setDraft] = useState<ReviewDraft | null>(null); const metrics = sampleWorkspaceMetrics(workspace);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setDraft(null); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  const detailPath = (id: string) => demo ? `/demo/flows/${id}` : `/flows/${id}`;
  const open = (flow: SampleFlow) => setDraft({ flow, decision: "Approved", owner: flow.owner === "Unassigned" ? "" : flow.owner, date: flow.nextReview === "Choose during review" ? "2026-10-20" : "2026-10-20", note: "" });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!draft) return; update((current) => ({ flows: current.flows.map((flow) => flow.id === draft.flow.id ? { ...flow, owner: draft.owner.trim() || "Unassigned", reviewStatus: draft.decision, nextReview: draft.decision === "Not needed" ? undefined : new Date(`${draft.date}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" }), environment: draft.decision === "Approved" ? "In use" : "Trial", status: flow.status === "No activity yet" && draft.decision === "Approved" ? "Live" : flow.status, activityNote: `${draft.decision} during sample review. ${draft.note.trim() || "No additional note."}` } : flow) })); setDraft(null); };
  const pending = workspace.flows.filter((flow) => flow.reviewStatus === "Needs review");
  return <AppShell workspaceLabel={demo ? "Demo workspace" : "Preview account"} userLabel={demo ? undefined : "test@gmail.com"} preview demo={demo} onSignOut={demo ? undefined : signOut} onReset={reset}><div className="space-y-5"><div><h1 className="text-xl font-semibold tracking-[-.02em]">Reviews</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Decide who owns trial workflows and when to check them again. This sample records decisions locally only.</p></div>
    <section className="grid overflow-hidden rounded-lg border border-slate-200 bg-white sm:grid-cols-3 sm:divide-x sm:divide-slate-200"><div className="border-b border-slate-200 p-4 sm:border-b-0"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Needs review</div><div className="mt-2 text-2xl font-semibold">{metrics.reviewCount}</div></div><div className="border-b border-slate-200 p-4 sm:border-b-0"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Needs an owner</div><div className="mt-2 text-2xl font-semibold">{workspace.flows.filter((flow) => flow.owner === "Unassigned").length}</div></div><div className="p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Open issues</div><div className="mt-2 text-2xl font-semibold">{metrics.issueCount}</div></div></section>
    <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-semibold">Review queue</h2><p className="mt-0.5 text-[11px] text-slate-400">A decision requires an owner and a next review date when the workflow remains in use.</p></div><div className="divide-y divide-slate-100">{pending.map((flow) => <div key={flow.id} className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between"><div><Link to={detailPath(flow.id)} className="text-sm font-semibold text-slate-900 hover:text-blue-700">{flow.name}</Link><div className="mt-1 text-xs text-slate-500">{flow.owner} · {flow.environment} · {flow.protection}</div><div className="mt-1 text-xs text-slate-500">{flow.nextReview ? `Next review: ${flow.nextReview}` : "Choose a next review date"}</div></div><button type="button" onClick={() => open(flow)} className="h-9 rounded-md bg-blue-600 px-3 text-xs font-semibold text-white">Review workflow</button></div>)}{pending.length === 0 ? <div className="px-4 py-10 text-center"><CheckCircle2 className="mx-auto h-5 w-5 text-emerald-600" /><div className="mt-2 text-sm font-medium">Nothing needs review</div><div className="mt-1 text-xs text-slate-500">New sample workflows will appear here until they are reviewed.</div></div> : null}</div></section>
    <section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="text-sm font-semibold">Ownership and review history</h2><div className="mt-3 divide-y divide-slate-100">{workspace.flows.filter((flow) => flow.reviewStatus !== "Needs review").map((flow) => <Link key={flow.id} to={detailPath(flow.id)} className="flex items-center justify-between gap-4 py-3 text-xs hover:text-blue-700"><span><strong className="text-slate-800">{flow.name}</strong><span className="ml-2 text-slate-500">{flow.owner} · {flow.reviewStatus}</span></span><span className="text-slate-400">{flow.nextReview ? `Review ${flow.nextReview}` : "No review planned"}</span></Link>)}</div></section>
    {draft ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4" role="dialog" aria-modal="true" aria-labelledby="review-title"><div className="w-full max-w-[500px] rounded-xl border border-slate-200 bg-white p-5 shadow-xl"><div className="flex items-start justify-between"><div><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Sample review</div><h2 id="review-title" className="mt-1 text-lg font-semibold">Review {draft.flow.name}</h2><p className="mt-1 text-xs text-slate-500">This updates the local sample only. It does not message anyone or change a live workflow.</p></div><button type="button" onClick={() => setDraft(null)} aria-label="Close review" className="rounded p-1 text-slate-400 hover:bg-slate-100"><X className="h-4 w-4" /></button></div><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-xs font-medium text-slate-700">Decision<select value={draft.decision} onChange={(event) => setDraft({ ...draft, decision: event.target.value as SampleReviewStatus })} className="mt-1.5 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm"><option>Approved</option><option>Needs review</option><option>Not needed</option></select></label><label className="block text-xs font-medium text-slate-700">Accountable owner<input required={draft.decision !== "Not needed"} value={draft.owner} onChange={(event) => setDraft({ ...draft, owner: event.target.value })} placeholder="Name of the owner" className="mt-1.5 h-10 w-full rounded-md border border-slate-300 px-3 text-sm" /></label>{draft.decision !== "Not needed" ? <label className="block text-xs font-medium text-slate-700">Next review date<input required type="date" value={draft.date} onChange={(event) => setDraft({ ...draft, date: event.target.value })} className="mt-1.5 h-10 w-full rounded-md border border-slate-300 px-3 text-sm" /></label> : null}<label className="block text-xs font-medium text-slate-700">Decision note<textarea required value={draft.note} onChange={(event) => setDraft({ ...draft, note: event.target.value })} rows={3} placeholder="Why is this decision appropriate?" className="mt-1.5 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" /></label><div className="flex gap-2"><button type="button" onClick={() => setDraft(null)} className="h-9 flex-1 rounded-md border border-slate-300 text-xs font-semibold text-slate-700">Cancel</button><button type="submit" className="h-9 flex-1 rounded-md bg-blue-600 text-xs font-semibold text-white">Save review</button></div></form></div></div> : null}
  </div></AppShell>;
}
