import { useState,type FormEvent } from "react";
import { Check,ChevronDown,Copy,X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

const platforms=["Zapier","n8n","Make","LangChain","Claude Code","Custom"];
export default function AddFlowModal({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}){
 const[name,setName]=useState(""),[platform,setPlatform]=useState("Zapier"),[model,setModel]=useState(""),[description,setDescription]=useState(""),[purpose,setPurpose]=useState(""),[team,setTeam]=useState("");
 const[more,setMore]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[createdId,setCreatedId]=useState<string|null>(null),[copied,setCopied]=useState(false),[credential,setCredential]=useState(""),[sample,setSample]=useState("");
 const endpoint=`${import.meta.env.VITE_SUPABASE_URL||"https://your-project.supabase.co"}/functions/v1/ingest/${createdId??"FLOW_ID"}`;
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Your session expired. Sign in again.");setLoading(false);return}const{data:member,error:memberError}=await supabase.from("workspace_members").select("workspace_id").eq("user_id",user.id).limit(1).maybeSingle();if(memberError||!member){setError(memberError?.message??"No workspace is available.");setLoading(false);return}const{data,error:insertError}=await supabase.from("flows").insert({name:name.trim(),platform,model:model.trim(),user_id:user.id,created_by:user.id,workspace_id:member.workspace_id,description:description.trim()||null,business_purpose:purpose.trim()||null,team_label:team.trim()||null,environment:"experiment",approval_status:"pending",protection_mode:"Monitor only",flow_enabled:true,control_state:"running"}).select("id").single();if(insertError||!data)setError(insertError?.message??"The workflow could not be created.");else setCreatedId(data.id);setLoading(false)};
 const issueCredential=async()=>{if(!createdId)return;setLoading(true);setError("");const{data,error:functionError}=await supabase.functions.invoke("credentials",{body:{flow_id:createdId}});if(functionError||!data?.credential)setError(functionError?.message??"Credential creation failed.");else setCredential(data.credential);setLoading(false)};
 const generateSample=async()=>{if(!createdId)return;setLoading(true);setError("");const{data,error:sampleError}=await supabase.rpc("seed_workflow_sample_activity",{p_flow_id:createdId});if(sampleError)setError(sampleError.message);else{const row=data?.[0];setSample(`${row?.run_count??24} sample runs · ${Number(row?.token_count??0).toLocaleString()} tokens · $${Number(row?.cost_usd??0).toFixed(2)}`)}setLoading(false)};
 const copy=async(value:string)=>{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)};
 const input="mt-1.5 h-10 w-full rounded-md border border-slate-300 px-3 text-sm";
 return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-xl border bg-white p-5 shadow-xl"><div className="flex justify-between gap-4"><div><h2 className="text-lg font-semibold">{createdId?"Choose how to start":"Add workflow"}</h2><p className="mt-1 text-xs text-slate-500">{createdId?"Connect real reporting or load sample activity now. You can change this later.":"Register the agent, its source, and who is responsible."}</p></div><button onClick={createdId?onCreated:onClose} aria-label="Close"><X className="h-4 w-4"/></button></div>
 {createdId?<div className="mt-5 space-y-4"><div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><Check className="h-4 w-4"/>{name} is registered.</div>
  <section className="rounded-lg border p-4"><h3 className="text-sm font-semibold">Connect real activity</h3><p className="mt-1 text-xs text-slate-500">Use this workflow-specific endpoint and a scoped reporting key. Provider master keys stay with {platform}.</p><div className="mt-3 flex gap-2 rounded-md bg-slate-50 p-2"><code className="min-w-0 flex-1 break-all text-[10px]">{endpoint}</code><button onClick={()=>copy(endpoint)} aria-label="Copy endpoint"><Copy className="h-4 w-4"/></button></div>{credential?<div className="mt-3 rounded-md border border-amber-200 bg-amber-50 p-3"><p className="text-xs font-semibold text-amber-900">Copy this reporting key now. It is shown once.</p><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 break-all text-[10px]">{credential}</code><button onClick={()=>copy(credential)} aria-label="Copy reporting key"><Copy className="h-4 w-4"/></button></div></div>:<button onClick={issueCredential} disabled={loading} className="mt-3 h-9 rounded-md bg-slate-900 px-3 text-xs font-semibold text-white">Create reporting key</button>}<p className="mt-2 text-[11px] text-slate-400">Send a stable event_id, tokens, cost, duration, and status after each run. A copied URL alone is not connected.</p></section>
  <section className="rounded-lg border border-blue-200 bg-blue-50 p-4"><h3 className="text-sm font-semibold text-blue-950">Try it with sample activity</h3><p className="mt-1 text-xs text-blue-800">Adds 24 clearly labeled synthetic hourly runs with varied tokens and spend. No provider is called.</p>{sample?<p className="mt-3 text-xs font-semibold text-emerald-700">{sample}</p>:<button onClick={generateSample} disabled={loading} className="mt-3 h-9 rounded-md border border-blue-300 bg-white px-3 text-xs font-semibold text-blue-700">Generate sample activity</button>}</section>
  {error?<p className="text-xs text-red-700">{error}</p>:null}<div className="flex gap-2"><a href={`/flows/${createdId}`} className="inline-flex h-9 flex-1 items-center justify-center rounded-md border text-xs font-semibold">View workflow</a><button onClick={onCreated} className="h-9 flex-1 rounded-md bg-blue-600 text-xs font-semibold text-white">Done</button></div>{copied?<p className="text-center text-xs text-emerald-700">Copied.</p>:null}</div>
 :<form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-xs font-medium">Name<input autoFocus required value={name} onChange={e=>setName(e.target.value)} className={input}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Source<select value={platform} onChange={e=>setPlatform(e.target.value)} className={input}>{platforms.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-medium">Model<input required value={model} onChange={e=>setModel(e.target.value)} className={input} placeholder="GPT-4o"/></label></div><button type="button" onClick={()=>setMore(!more)} className="inline-flex items-center gap-1 text-xs font-semibold text-blue-600">Owner and responsibility <ChevronDown className="h-3.5 w-3.5"/></button>{more?<div className="space-y-3 rounded-lg bg-slate-50 p-3"><label className="block text-xs">Owner / team<input value={team} onChange={e=>setTeam(e.target.value)} className={input} placeholder="Maya · Operations"/></label><label className="block text-xs">Responsibility<textarea value={purpose} onChange={e=>setPurpose(e.target.value)} rows={2} className="mt-1 w-full rounded-md border px-3 py-2"/></label><label className="block text-xs">Description<input value={description} onChange={e=>setDescription(e.target.value)} className={input}/></label></div>:null}{error?<p className="text-xs text-red-700">{error}</p>:null}<div className="flex gap-2"><button type="button" onClick={onClose} className="h-9 flex-1 rounded-md border text-xs font-semibold">Cancel</button><button type="submit" disabled={loading} className="h-9 flex-1 rounded-md bg-blue-600 text-xs font-semibold text-white">{loading?"Creating…":"Continue"}</button></div></form>}
 </div></div>
}
